### PR TITLE
Don't do anything with puppet_version is not set.

### LINKED ISSUE #35: rake beaker errors with vagrant-puppet-install loaded
Have been working on getting a sample rake beaker going.
At first,I believed it was a problem with my local app... 
Tried downloading a sample project from puppetlabs.

My machine: ubuntu 14.04

Here are the steps to reproduce... (with vagrant-puppet-install already loaded and available).

- vagrant **uninstall** plugin vagrant-puppet-install
- clone a sample repo ie: (puppetlabs/puppetlabs-motd)
- make no modifications
- rake spec (works fine)
- rake beaker (works fine)

- vagrant **install**plugin vagrant-puppet-install
- rake spec (works fine)
- rake beaker... (exception)

```
/home/mike/.rvm/gems/ruby-2.2.4/gems/beaker-2.31.0/lib/beaker/hypervisor/vagrant.rb:196:in `block (2 levels) in vagrant_cmd': Failed to exec 'vagrant up'. Error was /home/mike/.vagrant.d/gems/gems/vagrant-puppet-install-3.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:65:in `default_install_url': undefined method `match' for nil:NilClass (NoMethodError) (RuntimeError)
	from /home/mike/.vagrant.d/gems/gems/vagrant-puppet-install-3.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:58:in `find_install_script'
	from /home/mike/.vagrant.d/gems/gems/vagrant-puppet-install-3.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:16:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:90:in `new'
```

The results were reproduced with ruby 1.9.3 (I thought I'd give that a try just in case).

Let me know if there's anything else I can do to help.

### PR DESCRIPTION
**Pull request by glenjamin**
Fixes #35

### CODE REVIEW

**Comment by razorsedge** [comment]
:+1:  I need this.

**Comment by eyecatchup** [comment]
:+1: please merge :)

**Comment by stevenrombauts** [comment]
:+1: Please merge this one! I need to uninstall and reinstall between every other Vagrant box that I want to run :)

**Comment by petems** [comment]
@glenjamin Thanks for your contribution! Will get this out in a release now :+1:

**Comment by petems** [comment]
Released with 3.1.0! :smile:

**Comment by glenjamin** [comment]
Awesome, thanks!

**Comment by eyecatchup** [comment]
:+1:

**Comment by stevenrombauts** [comment]
Excellent, everything's back to normal. Thank you!

**Pull request merged**
